<?xml version="1.0" encoding="utf-8"?>
<ExperimentalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExperimentTitle>紫色石磊溶液滴加盐酸实验</ExperimentTitle>
  <CL_Objects>
    <CL_Object>
      <Name>HCl溶液</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
        <Operation>
          <Name>Hold</Name>
        </Operation>
        <Operation>
          <Name>Rota</Name>
        </Operation>
        <Operation>
          <Name>Pull</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0.0004</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>50</a>
      </LiquidColor>
      <Id>4a6c52aa-9f15-435e-b159-a9f5d0b25d4d</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>玻璃棒</Name>
      <Model>1</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Common</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>009a6cd1-b301-4474-8ceb-2e27c7f8eabe</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>紫色石磊溶液</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
        <Operation>
          <Name>Hold</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0.0004</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>0</g>
        <b>255</b>
        <a>200</a>
      </LiquidColor>
      <Id>4c8e0724-9359-4148-97c5-b0c934353fc3</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
  </CL_Objects>
  <Operations>
    <Operation>
      <Name>Move</Name>
    </Operation>
    <Operation>
      <Name>Hold</Name>
    </Operation>
    <Operation>
      <Name>Rota</Name>
    </Operation>
    <Operation>
      <Name>Pull</Name>
    </Operation>
    <Operation>
      <Name>Other1</Name>
    </Operation>
  </Operations>
  <SceneObjects>
    <CL_Object>
      <Name>HCl溶液</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
        <Operation>
          <Name>Hold</Name>
        </Operation>
        <Operation>
          <Name>Rota</Name>
        </Operation>
        <Operation>
          <Name>Pull</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0.0004</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>50</a>
      </LiquidColor>
      <Id>4a6c52aa-9f15-435e-b159-a9f5d0b25d4d</Id>
      <Position>
        <x>0.133579344</x>
        <y>-8.9854E-06</y>
        <z>0.218776256</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>紫色石磊溶液</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
        <Operation>
          <Name>Hold</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0.0004</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>0</g>
        <b>255</b>
        <a>200</a>
      </LiquidColor>
      <Id>4c8e0724-9359-4148-97c5-b0c934353fc3</Id>
      <Position>
        <x>0.122463234</x>
        <y>-3.85940075E-06</y>
        <z>-0.16302757</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
  </SceneObjects>
  <EventClassifys>
    <string>默认</string>
  </EventClassifys>
  <EventInfos>
    <ArrayOfEventInfo>
      <EventInfo>
        <Name>初始化</Name>
        <Remark>这是一个事件案列</Remark>
        <EventType>GameInitialize</EventType>
        <Action>
          <values>
            <CLValue>
              <value xsi:type="xsd:string">欢迎来到化学实验室</value>
              <parameterindex>-1</parameterindex>
              <parameterreflect />
            </CLValue>
            <CLValue xsi:nil="true" />
          </values>
          <type>ShowTip</type>
        </Action>
      </EventInfo>
      <EventInfo>
        <Name>first</Name>
        <Remark>这里可以写一些备注来说明这个事件的用途</Remark>
        <EventType>AnyObjectSelected</EventType>
        <Condition>
          <condition1>
            <value>
              <value xsi:type="xsd:string">1</value>
              <parameterindex>-1</parameterindex>
              <parameterreflect />
            </value>
            <conditiontype>val</conditiontype>
          </condition1>
          <condition2>
            <value>
              <value xsi:type="xsd:string">0</value>
              <parameterindex>-1</parameterindex>
              <parameterreflect />
            </value>
            <conditiontype>val</conditiontype>
          </condition2>
          <conditiontype>greater</conditiontype>
        </Condition>
        <Action>
          <values>
            <CLValue>
              <parameterindex>0</parameterindex>
              <name>触发物体0</name>
              <parameterreflect>
                <string>Name</string>
              </parameterreflect>
            </CLValue>
            <CLValue xsi:nil="true" />
          </values>
          <type>ShowTip</type>
        </Action>
      </EventInfo>
      <EventInfo>
        <Name>color</Name>
        <Remark>紫色石磊溶液滴加盐酸后的颜色变换</Remark>
        <EventType>AnyVesselPourLiquidToOtherVessel</EventType>
        <Condition>
          <condition1>
            <condition1>
              <value>
                <parameterindex>0</parameterindex>
                <name>触发物体0</name>
                <parameterreflect>
                  <string>Name</string>
                </parameterreflect>
              </value>
              <conditiontype>val</conditiontype>
            </condition1>
            <condition2>
              <value>
                <value xsi:type="xsd:string">HCl溶液</value>
                <parameterindex>-1</parameterindex>
                <parameterreflect />
              </value>
              <conditiontype>val</conditiontype>
            </condition2>
            <conditiontype>equal</conditiontype>
          </condition1>
          <condition2>
            <condition1>
              <value>
                <parameterindex>1</parameterindex>
                <name>触发物体1</name>
                <parameterreflect>
                  <string>Name</string>
                </parameterreflect>
              </value>
              <conditiontype>val</conditiontype>
            </condition1>
            <condition2>
              <value>
                <value xsi:type="xsd:string">紫色石磊溶液</value>
                <parameterindex>-1</parameterindex>
                <parameterreflect />
              </value>
              <conditiontype>val</conditiontype>
            </condition2>
            <conditiontype>equal</conditiontype>
          </condition2>
          <conditiontype>and</conditiontype>
        </Condition>
        <Action>
          <values>
            <CLValue>
              <parameterindex>1</parameterindex>
              <name>触发物体1</name>
              <parameterreflect>
                <string>Id</string>
              </parameterreflect>
            </CLValue>
            <CLValue>
              <value xsi:type="xsd:string">255,0,100,100</value>
              <parameterindex>-1</parameterindex>
              <parameterreflect />
            </CLValue>
          </values>
          <type>ChangeLiquidColor</type>
        </Action>
      </EventInfo>
    </ArrayOfEventInfo>
  </EventInfos>
</ExperimentalInfo>