<?xml version="1.0" encoding="utf-8"?>
<ExperimentalInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ExperimentTitle />
  <CL_Objects>
    <CL_Object>
      <Name>烧杯</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>90813ee3-34c3-4b09-b09b-6f79e119b13a</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>玻璃棒</Name>
      <Model>1</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Common</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>量筒</Name>
      <Model>2</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>烧瓶</Name>
      <Model>3</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>4e8d8641-cd84-4408-b8cc-fc0b65a6924a</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>锥形瓶</Name>
      <Model>4</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>ae320f9c-65e2-406f-aca2-1494a40f26ca</Id>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>试管</Name>
      <Model>5</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Position>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
  </CL_Objects>
  <Operations>
    <Operation>
      <Name>Move</Name>
    </Operation>
    <Operation>
      <Name>Hold</Name>
    </Operation>
    <Operation>
      <Name>Rota</Name>
    </Operation>
    <Operation>
      <Name>Pull</Name>
    </Operation>
    <Operation>
      <Name>Other1</Name>
    </Operation>
  </Operations>
  <SceneObjects>
    <CL_Object>
      <Name>烧杯</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>90813ee3-34c3-4b09-b09b-6f79e119b13a</Id>
      <Position>
        <x>0.03683991</x>
        <y>-1.59442425E-06</y>
        <z>-0.225210026</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>烧杯</Name>
      <Model>0</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>90813ee3-34c3-4b09-b09b-6f79e119b13a</Id>
      <Position>
        <x>0.0182564184</x>
        <y>-1.57058239E-05</y>
        <z>0.13928172</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>锥形瓶</Name>
      <Model>4</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>ae320f9c-65e2-406f-aca2-1494a40f26ca</Id>
      <Position>
        <x>0.179333374</x>
        <y>0</y>
        <z>0.3687303</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>锥形瓶</Name>
      <Model>4</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>ae320f9c-65e2-406f-aca2-1494a40f26ca</Id>
      <Position>
        <x>0.0794638246</x>
        <y>0</y>
        <z>-0.5522907</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
    <CL_Object>
      <Name>烧瓶</Name>
      <Model>3</Model>
      <ModelSize>1</ModelSize>
      <Operations>
        <Operation>
          <Name>Move</Name>
        </Operation>
      </Operations>
      <Type>Vessel</Type>
      <Liquidvolume>0</Liquidvolume>
      <LiquidTemperature>20</LiquidTemperature>
      <LiquidColor>
        <r>255</r>
        <g>255</g>
        <b>255</b>
        <a>0</a>
      </LiquidColor>
      <Id>4e8d8641-cd84-4408-b8cc-fc0b65a6924a</Id>
      <Position>
        <x>0.331197351</x>
        <y>0</y>
        <z>-0.0517185219</z>
      </Position>
      <EulerAngle>
        <x>0</x>
        <y>0</y>
        <z>0</z>
      </EulerAngle>
    </CL_Object>
  </SceneObjects>
  <EventClassifys>
    <string>默认</string>
  </EventClassifys>
  <EventInfos>
    <ArrayOfEventInfo>
      <EventInfo>
        <Name>初始化</Name>
        <Remark>这是一个事件案列</Remark>
        <EventType>GameInitialize</EventType>
        <Action>
          <values>
            <CLValue>
              <value xsi:type="xsd:string">欢迎来到化学实验室</value>
              <parameterindex>-1</parameterindex>
              <parameterreflect />
            </CLValue>
            <CLValue xsi:nil="true" />
          </values>
          <type>ShowTip</type>
        </Action>
      </EventInfo>
    </ArrayOfEventInfo>
  </EventInfos>
</ExperimentalInfo>